### ISSUE TITLE
Hi Thank you for your useful lecture

### ISSUE THREAD

**Issue by linnabrown** [timeu/gwas-lecture#1]
In Lec12. I tried to install `limix` but still shows the following error

```
No module named 'limix.util'
```

**Comment by timeu** [comment]
Make sure to activate the conda environment before you start the jupyter notebook:

```
conda activate gwas-lecture
jupyter notebook
```

**Comment by linnabrown** [comment]
Got it thank you so much! limix 3.0.0 rewrote a lot of api so some features disappear. You used 1.0.18. I got it. Thanks for great help!!!

**Comment by timeu** [comment]
No worries.
Yes we need to update the lecture for the new Limix 3.0 at some point.
